name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        # Use --legacy-peer-deps for the time being while we work out Rollup
        # dep issues.
        run: |
          cd /home/runner/work/ha-custom-cards/ha-custom-cards
          npm install --legacy-peer-deps
          npm run build
